version: '3.9'
    
services:
  kong.db.com.br:
    image: postgres:14-alpine
    container_name: kong.db.com.br
# Uncoment de parameter below after you start the container for the first time
#    user: postgres
    volumes:
      - "./postgresql/kong-db:/var/lib/postgresql/data:z"
    ports:
      - "15432:5432"
    env_file:
      - ./env/kong.env
    deploy:
      restart_policy:
        condition: always
        max_attempts: 5
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    networks:
      kong-keycloak-net:
        ipv4_address: 192.168.50.10

  kong:  
    build: ./build
    container_name: kong
    depends_on:
      - kong.db.com.br
#    command: "kong migrations bootstrap"
#    command: "kong migrations up" 
#    command: "kong migrations finish"
    ports:
      - "80:8000" # Listener
      - "443:8443" # Listener (SSL)
#      - "8001:8001" # Admin API
#      - "8444:8444" # Admin API (SSL)
      - "8002:8002" # Kong Manager OSS
    extra_hosts:
      - "server-name-here.com.br:127.0.0.1" 
    volumes:
      - "./kong/var/log/kong:/var/log/kong:z"
      - "./kong/etc/kong:/etc/kong:z"
#      - "./kong/ModSecurity:/ModSecurity"
#      - "./kong/usr/local/coreruleset:/usr/local/coreruleset"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./env/kong.env
    deploy:
      restart_policy:
        condition: always
        max_attempts: 5
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    networks:
      kong-keycloak-net:
        ipv4_address: 192.168.50.11

networks:
  kong-keycloak-net: 
    name: kong-keycloak-net
    ipam:
      config:
        - subnet: "192.168.50.0/24"